trigger:
- master

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/myApp.zip'
    replaceExistingArchive: true
  displayName: 'Archive Build Folder to Zip'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/myApp.zip'
    artifactName: 'myAppZip'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts - myApp.zip'
